// flow-typed signature: 7b860b661bc4a3ecb8f58e35da37950a
// flow-typed version: <<STUB>>/flow-status-webpack-plugin_v^0.1.7/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-status-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-status-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'flow-status-webpack-plugin/index' {
  declare module.exports: $Exports<'flow-status-webpack-plugin'>;
}
declare module 'flow-status-webpack-plugin/index.js' {
  declare module.exports: $Exports<'flow-status-webpack-plugin'>;
}
