// flow-typed signature: ccb1bb032d74e653a74320f7b6ac31df
// flow-typed version: <<STUB>>/stylelint-config-standard_v^15.0.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-standard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-standard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stylelint-config-standard/index' {
  declare module.exports: $Exports<'stylelint-config-standard'>;
}
declare module 'stylelint-config-standard/index.js' {
  declare module.exports: $Exports<'stylelint-config-standard'>;
}
